./sig build 1 &
./sig build 2 &
./sig build 3 &
./sig build 4 &
./sig build 5 &
./sig build 6 &
./sig build 7 &
./sig build 8 &
./sig build 9 &
./sig build 10 &
./sig build 11 &
./sig build 12 &
./sig build 13 &
./sig build 14 &
./sig build 15 &
./sig build 16 &
./sig build 17 &
./sig build 18 &
./sig build 19 &
./sig build 20 &